### ISSUE TITLE
'functions and lists' to help automate plots?  (Agree on this, make a protocol)

### ISSUE THREAD

**Issue by daaronr** [rethinkpriorities/how-to-visualize#11]
See discussion [here](https://github.com/rethinkpriorities/rp-r-package/commit/9051318bfeb171282bd29029aea933dcaec52604)

**Comment by WillemSleegers** [comment]
I'm not sure whether we settled on this but to me `ggplot2` is already the solution to automating the creation of plots. Further automation will be counter-productive to me in most cases.

**Comment by daaronr** [comment]
I definitely understand that you prefer not to create functions that nest ggplot2, which is fair. (I think I still do, but I see your point). 

I guess the thing to still do here might be to post a canonical example of 'each of the categories of plots we use most frequently', using ggplot2? Otherwise I will be scraping around each time for a while to try to remember how it worked.

**Comment by WillemSleegers** [comment]
Yeah that's the goal. The idea is to have it be a collection of useful code snippets that you can grab and modify to suit your particular use case.
