### ISSUE TITLE
Should we use tibbles as inputs for ggplot parameters? 

### ISSUE THREAD

**Issue by daaronr** [rethinkpriorities/how-to-visualize#12]
See https://albert-rapp.de/post/2022-03-25-functional-programming-when-geoms-are-not-vectorized/

@WillemSleegers thoughts?

**Comment by WillemSleegers** [comment]
The link doesn't work.

**Comment by daaronr** [comment]
I think it was this content: https://www.r-bloggers.com/2022/03/how-to-use-functional-programming-for-ggplot/

**Comment by daaronr** [comment]
https://albert-rapp.de/posts/ggplot2-tips/09_functional_programming_ggplot/09_functional_programming_ggplot.html almost the same, but maybe nicer formatted

**Comment by WillemSleegers** [comment]
Okay works. I don’t think this will be useful very often. I think we can close this issue for now and reopen if this will come up.
