### ISSUE TITLE
Integrate notes on visualizations into

### ISSUE THREAD

**Issue by daaronr** [rethinkpriorities/how-to-visualize#2]
how-to-visualize repo

**Comment by WillemSleegers** [comment]
Closing because this is not an issue.

**Comment by daaronr** [comment]
So this is an 'ongoing to do' I guess. I was using the 'issues' within the Github project framework for a Kanban ... at one point. But I can see the difficulty here; if you think of 'issues' in the standard way, it suggests something concrete that needs to be fixed. 

So maybe the solution is either 
1. to have some other category of issue ('improvement' or something),
2. to not make the elements of a 'project'  be 'issues' (but then there's limited functionality; although maybe the 'new project board format' fixes this)
3. to not use the Projects feature in github to do project management and keep track of todos. (What's a good alternative, though?)

**Comment by WillemSleegers** [comment]
I'm fine with only issues to refer to concrete issues. So if there's something specific we need to do, we create an issue. 

I'm not sure there's anything else that we need to keep track of. Is there?

**Comment by daaronr** [comment]
OK. I was sort of using this to keep track of 'things I/we want to do and
focus on when we have time' ... i.e., what is sometimes called 'project
management'. But here there is no individual 'project manager'.

Anyways, probably best to move that 'general goals stuff' to a different
system, given the limitations here (esp. 'issues' being confusing).

**Comment by WillemSleegers** [comment]
I think we can use Issues for that _if_ you have something concrete that we need to do. No need to have a todo that says something like 'work on this repo'.

So I think this will do the trick.
