### ISSUE TITLE
tool to auto-include package references

### ISSUE THREAD

**Issue by daaronr** [rethinkpriorities/how-to-visualize#6]
https://github.com/rethinkpriorities/how-to-visualize/blob/41ef37cdfc94b4baca1b605c5ab5fe249de3928d/index.Rmd#L63

Why is this set to `include=FALSE` @WillemSleegers  -- do you have a working system to automate package citation?

**Comment by WillemSleegers** [comment]
Include means it will still run, so it creates the .bib file. I don't think it needs to be visible, though.

**Comment by daaronr** [comment]
but I thought you set it to `Include=FALSE`

**Comment by WillemSleegers** [comment]
> include = FALSE prevents code and results from appearing in the finished file. R Markdown still runs the code in the chunk, and the results can be used by other chunks.

Yeah, bit counterintuitive but apparently it should still run.

**Comment by daaronr** [comment]
sorry, I got my syntax mixed up!
